### ISSUE TITLE
Week 3 Out of Class Work :  Review Videos

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2023_Team1#15]
How to write user stories 
[http://bit.ly/2IMDQwJ](http://bit.ly/2IMDQwJ)
[http://bit.ly/2I1gZMM](http://bit.ly/2I1gZMM) : And it is in a Scottish accent!

- [x] Jie An 
- [x] Emery Donovan 
- [x] Lida Jiang 
- [x] Yiwen Teng

@emerydonovan, @yiwenteng, @lidajiang19, @jieanjie

**Comment by emerydonovan** [comment]
What stood out to me about these videos that was new was the idea of acceptance criteria for when a user story is done - seeing the visual of the cards helped underscore this for me. It was also helpful to have a project context in which to see all the potential users and how the backlog of cards informs the work. Seeing it on index cards rather than a digital platform helped me understand the actual system better rather!

**Comment by akallish** [comment]
@emerydonovan thanks for your comments. This is why we are using Mural first to affinity map sub hills to epic names and then writing stories. Am glad the video helped.
