### ISSUE TITLE
Activate texting

### ISSUE THREAD

**Issue by yiwenteng** [IITIDIDX597/F2023_Team1#18]
As a regiester, I want a one-day prior text reminder for wellness events, so that I can plan my day accordingly and not miss the event.

**Comment by akallish** [comment]
@emerydonovan @jieanjie @yiwenteng @lidajiang What about this iteration :

**As a :** regiester
Comment : Not sure what a register is. Should this be employee?
**I want :** a one-day prior text reminder for wellness events
Comment : This is clear. But this could be more specific. Should emphasize the closest MWB registration event to my department. It might be convenient to have a link to a calendar file that would go into my work calendar.
**So that :** I can plan my day accordingly and not miss the event.
Comment : This is clear

**Comment by emerydonovan** [comment]
As a... employee registering for MWB
I want... a text one day prior to wellness event that tells me the time, closest location to my department and has a calendar link for the event 
So that... I can plan my day accordingly and not miss the event
