### ISSUE TITLE
Offer onsite registration 

### ISSUE THREAD

**Issue by yiwenteng** [IITIDIDX597/F2023_Team1#19]
As a food service employee
I want on-site registration to be quick
so that I can do it on my break.

**Comment by akallish** [comment]
@emerydonovan @jieanjie @yiwenteng @lidajiang What about this iteration :

- As a food service employee
Comment : this is good
- I want on-site registration to be quick
Comment : I want on site registration opportunities five minutes from my department, or in my department
- so that I can do it on my break.
Comment : So that I can easily sign up in ten minutes on my break

**Comment by emerydonovan** [comment]
As a food service employee
I want on-site MWB registration events to take place in my department and last 5 minutes or less 
So that I can easily sign up while on my breaks.
