### ISSUE TITLE
Create a poster campaign

### ISSUE THREAD

**Issue by yiwenteng** [IITIDIDX597/F2023_Team1#20]
As a budget-conscious employee,
I want: to see posters in the break zone that showcase the financial benefits of MWB,
So that I can understand how it might help me save money for essentials.

**Comment by akallish** [comment]
@emerydonovan @jieanjie @yiwenteng @lidajiang19 This is a good story but can be refined : 

- As a budget-conscious employee
Comment : this is good
- I want: to see posters in the break zone that showcase the financial benefits of MWB
Comment : When I view MWB posters they should highlight the financial benefits
- So that I can understand how it might help me save money for essentials.
Comment : And if interested, there is a QR code on the poster so I can use my phone to begin sign up if interested

**Comment by emerydonovan** [comment]
As a budget-conscious employee, I want to see posters that highlight the financial benefits of MWB, so that I can understand why MWB might be relevant to me.

**Comment by akallish** [comment]
@emerydonovan i would be more specific on the I want and so that so the story is testable.

**Comment by emerydonovan** [comment]
DRAFT:
**User story**
- As a budget conscious employee, I want to know how much money I will save from participating in MWB, so that I can decide whether or not it's worthwhile for me to register.

**Acceptance criteria**
- Given that I'm a budget conscious employee, when I quickly glance at the MWB poster I immediately see that I will save $600 then I can scan a QR code with my phone if I decide I want to sign up.

**Comment by akallish** [comment]
@emerydonovan good iteration 0. The last part could be clearer 

Given that I'm a budget conscious employee
When I quickly glance at the MWB poster I immediately see that I will save $600 
Then if I decide I want to sign up, I can scan a QR code with my phone
