### ISSUE TITLE
Highlight MWB in orientation

### ISSUE THREAD

**Issue by yiwenteng** [IITIDIDX597/F2023_Team1#21]
As an UCM employee,
I want to access MWB without blocks and difficulties, 
So that I do not need to spend extra effort to figure out any registration issues.

**Comment by akallish** [comment]
@emerydonovan, @yiwenteng, @lidajiang19, @jieanjie Good iteration 0. Consider this iteration and refine :

As a: As an UCM employee
Comment : This is good
I want: I want to access MWB without blocks and difficulties
Comment : Your sub hill statement has several parts to it so it is hard to trace to a specific one. I would be clear as to which part of the sub-hill statement the story traces to. I assume this is about "generate targeted message" Consider "to benefit from SMS messaging links to the MWB registration platform with organizational single sign on to sign in and most of my official information is already filled in" 
So that : So that I do not need to spend extra effort to figure out any registration issues.
Comment : Consider "so I can focus on choosing a registration date/time and register within two minutes"

**Comment by emerydonovan** [comment]
As a UCM employee, I want to learn about MWB during employee orientation so that I can begin accessing the financial and health benefits of the program as soon as possible.

As a UCM employee, I want to have a quick link to sign up for MWB during employee orientation so that I can register for the program right away before I get busier with my new job.

**Comment by akallish** [comment]
@emerydonovan this should be two stories
