### ISSUE TITLE
Build a champion network

### ISSUE THREAD

**Issue by yiwenteng** [IITIDIDX597/F2023_Team1#22]
As an employee who has never heard about MWB, I want the department champion to be knowledgeable about MWB so I can make an informed decision about whether or not to participate.

**Comment by akallish** [comment]
@emerydonovan @jieanjie @yiwenteng @lidajiang19 Thanks for posting this story. We have missing information here:

• goal statement
• hill statement
• subhill statement
• then story

Remember, in agile all work should be traced to higher level goals to make sure people doing the work understand the overall larger value to secure. Otherwise it is a task out of context.

**Comment by akallish** [comment]
@emerydonovan @jieanjie @yiwenteng @lidajiang19 Below are my comments on this story:

- As an employee who has never heard about MWB
Comment : This is OK

I want the department champion to be knowledgeable about MWB 
Comment : Knowledgable about what? Be more specific 

so I can make an informed decision about whether or not to participate.
Comment : Since I cannot see the subhill statement I am not sure if this is the right statement. Remember this is the benefit part of the story. It should be testable. Right now the test is if they want to sign up to MWB. I believe it should focus on what would get an employee to sign up. 

@emerydonovan what do you think?

**Comment by akallish** [comment]
@emerydonovan @jieanjie @yiwenteng @lidajiang19 In terms of the epic tag : It should say "Epic : (Name of epic). Remember you need to differentiate one epic from another.

**Comment by emerydonovan** [comment]
GOAL: For the UChicago Medicine HR team who wants to increase registration rates for the MyWellbeing employee wellness program by 24%, the MWB communication toolkit has all the components to increase awareness + staff engagement with MWB so that more employees can engage with the health resources they need to be as healthy as possible.

Hill statement: The UCM HR team wants to increase MWB registration rates amongst employees by providing pathways specifically tailored for underreached employees to be able to register on the MWB platform.

Subhill statement: Build a champion network starting in Fall 2023 by HR staff member emailing department managers to identify possible candidates for a champion network pilot, attending departmental meetings to recruit candidates and co-designing a pilot with at least 4 candidates over the course of 2 one hour workshops. Launch the pilot program in one department in Spring 2023. Run it for 2 months and gather feedback via qualitative surveys from 15 employees to assess pilot feedback. Use feedback to refine.

Story: As an employee who has never heard about MWB, I want the department champion to clearly explain what benefits I would get out of enrolling in MWB so I can make an informed decision about whether or not to register.

**Comment by akallish** [comment]
@emerydonovan can you be more specific on the financial benefits? Can the so that statement focus more on signing up?
