### ISSUE TITLE
Optimize emails

### ISSUE THREAD

**Issue by yiwenteng** [IITIDIDX597/F2023_Team1#23]
As a :busy employee,
I want: MWB emails to be concise with clear action items
So that :  can quickly understand the content without reading long paragraphs

GOAL: For the UChicago Medicine HR team who wants to increase registration rates for the MyWellbeing employee wellness program by 24%, the MWB communication toolkit that has all the engagement components to increase awareness + staff engagement with MWB so that more employees can engage with the health resources they need to be as healthy as possible.

SUBHILL: Activate texting by add MWB on the text contact name, create texts with a singular focus and in fragments, generate targeted message , 'opt-out' strategy, highlight saving and include links to FAQs, and make sure text under 220 characters.

**Comment by akallish** [comment]
As a: busy employee
Comment : This is good
I want: MWB emails to be concise with clear action items
Comment : Your sub hill statement has several parts to it so it is hard to trace to a specific one. I would be clear as to which part of the sub-hill statement the story traces to. I assume this is about "singular focus and in fragments" Consider "MWB emails to be no longer than 220 characters so that I can quickly understand the benefits 
So that : can quickly understand the content without reading long paragraphs
Comment : Consider "So I can make up my mind and press the "sign up" button to begin to register for the program."

**Comment by emerydonovan** [comment]
I think we have the wrong subhill statement - new one is:
SUBHILL: Optimize emails by easy steps and an action item, reduce the load on the user to read long walls of text, making people more likely to absorb and remember information. Revise the existing email template to meet specific requirements by incorporating the MWB logo, introducing splash ads, and establishing a regular email sending schedule.

As a busy employee...
I want MWB emails to be concise, with clear action items so that I can quickly click any links connected to MWB deadlines.

**Comment by akallish** [comment]
@emerydonovan your teams sub hill statement are too large. There should be one function per sub hill

**Comment by emerydonovan** [comment]
SUBHILL: Optimize HR emails so that they are easy for employees to skim and learn from.

**Comment by emerydonovan** [comment]
we can split these up into stories: 
- As a busy employee, i easy steps and an action item
-  reduce the load on the user to read long walls of text so that people are more likely to absorb and remember information. 
-  Revise the existing email template to meet specific requirements by incorporating the MWB logo
-  Revise the existing email template to introduce splash ads
- Establish a regular email sending schedule.

**Comment by emerydonovan** [comment]
bullet point #2:

As a.... busy employee
I want... MWB emails that I can read and understand in 30 seconds or less
So that... I can get key updates without additional effort.

**Comment by yiwenteng** [comment]
As a: busy employee
I want email to have 3 easy steps to sign up for MWB
So that : I can make up my mind and press the "sign up" button to begin to register for the program.

**Comment by jieanjie** [comment]
Sub Hill: Revise the existing email template to meet specific requirements by incorporating the MWB logo

As an employee who receives an email from MWB
I want to see the logo of  an email at a glance which helps me know where it comes from 
So that I can easily discern it and decide how to deal with it.

**Comment by lidajiang19** [comment]
- Revise the existing email template to introduce splash ads

As a busy employee, I want to learn MWB benefits at a glance, so that I can know why MWB is necessary to me.
